blueprint:
  name: Hue Switch Control
  description: >
    Multi-press + hold controller for Philips Hue Dimmer Switch (Hue integration).
    - Press is mapped to hue_event type=initial_press (short_release ignored)
    - Hold is mapped to hue_event type=long_press (repeat + long_release ignored)
    - Multi-press is detected per device + per button within a time window (max 4).
  domain: automation
  source_url: https://raw.githubusercontent.com/robbartn/hue_switch_control/refs/heads/main/hue_switch_control.yaml

input:
  switches:
    name: Hue dimmer switch devices
    description: Select one or more Hue dimmer switches.
    selector:
      device:
        multiple: true
        filter:
          - integration: hue
            manufacturer: Signify Netherlands B.V.
            model: Hue dimmer switch

  multi_press_window:
    name: Multi press window (seconds)
    description: Time window to collect repeated presses (per device + button).
    default: 10
    selector:
      number:
        min: 1
        max: 20
        step: 1
        mode: slider
        unit_of_measurement: seconds

  on_press_1:
    name: On - Press 1
    default: []
    selector: { action: {} }
  on_press_2:
    name: On - Press 2
    default: []
    selector: { action: {} }
  on_press_3:
    name: On - Press 3
    default: []
    selector: { action: {} }
  on_press_4:
    name: On - Press 4
    default: []
    selector: { action: {} }
  on_hold:
    name: On - Hold
    default: []
    selector: { action: {} }

  up_press_1:
    name: Up - Press 1
    default: []
    selector: { action: {} }
  up_press_2:
    name: Up - Press 2
    default: []
    selector: { action: {} }
  up_press_3:
    name: Up - Press 3
    default: []
    selector: { action: {} }
  up_press_4:
    name: Up - Press 4
    default: []
    selector: { action: {} }
  up_hold:
    name: Up - Hold
    default: []
    selector: { action: {} }

  down_press_1:
    name: Down - Press 1
    default: []
    selector: { action: {} }
  down_press_2:
    name: Down - Press 2
    default: []
    selector: { action: {} }
  down_press_3:
    name: Down - Press 3
    default: []
    selector: { action: {} }
  down_press_4:
    name: Down - Press 4
    default: []
    selector: { action: {} }
  down_hold:
    name: Down - Hold
    default: []
    selector: { action: {} }

  off_press_1:
    name: Off - Press 1
    default: []
    selector: { action: {} }
  off_press_2:
    name: Off - Press 2
    default: []
    selector: { action: {} }
  off_press_3:
    name: Off - Press 3
    default: []
    selector: { action: {} }
  off_press_4:
    name: Off - Press 4
    default: []
    selector: { action: {} }
  off_hold:
    name: Off - Hold
    default: []
    selector: { action: {} }

mode: parallel
max: 50

trigger:
  - platform: event
    event_type: hue_event

variables:
  switches: !input switches
  window_s: !input multi_press_window

action:
  - variables:
      d: "{{ trigger.event.data }}"
      device_id: "{{ d.device_id | default('', true) }}"
      press_type: "{{ d.type | default('', true) }}"
      subtype_raw: "{{ d.subtype | default('', true) }}"
      button: >-
        {% set s = subtype_raw %}
        {% if s in [1, '1', 'on', 'turn_on', 'button_1'] %}
          on
        {% elif s in [2, '2', 'up', 'dim_up', 'button_2'] %}
          up
        {% elif s in [3, '3', 'down', 'dim_down', 'button_3'] %}
          down
        {% elif s in [4, '4', 'off', 'turn_off', 'button_4'] %}
          off
        {% else %}
          unknown
        {% endif %}

  - condition: template
    value_template: >-
      {{ device_id != '' and (switches | default([])) is iterable and device_id in switches and button != 'unknown' }}

  - choose:
      # Hold (long_press). Ignore repeat and long_release.
      - conditions:
          - condition: template
            value_template: "{{ press_type == 'long_press' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'on' }}"
                sequence: !input on_hold
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'up' }}"
                sequence: !input up_hold
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'down' }}"
                sequence: !input down_hold
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'off' }}"
                sequence: !input off_hold

      # Press (initial_press). Ignore short_release.
      - conditions:
          - condition: template
            value_template: "{{ press_type == 'initial_press' }}"
        sequence:
          - variables:
              count: 1

          # Count additional presses of the same device + same button within the window (max 4)
          - repeat:
              while:
                - condition: template
                  value_template: "{{ count < 4 }}"
              sequence:
                - wait_for_trigger:
                    - platform: event
                      event_type: hue_event
                      event_data:
                        type: initial_press
                  timeout:
                    seconds: "{{ window_s }}"
                  continue_on_timeout: false

                - condition: template
                  value_template: >-
                    {{
                      wait.trigger is not none and
                      wait.trigger.event.data.device_id == device_id and
                      wait.trigger.event.data.subtype == subtype_raw
                    }}

                - variables:
                    count: "{{ count + 1 }}"

          # Execute actions for the final count
          - choose:
              # ON
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'on' and count == 1 }}"
                sequence: !input on_press_1
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'on' and count == 2 }}"
                sequence: !input on_press_2
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'on' and count == 3 }}"
                sequence: !input on_press_3
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'on' and count == 4 }}"
                sequence: !input on_press_4

              # UP
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'up' and count == 1 }}"
                sequence: !input up_press_1
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'up' and count == 2 }}"
                sequence: !input up_press_2
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'up' and count == 3 }}"
                sequence: !input up_press_3
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'up' and count == 4 }}"
                sequence: !input up_press_4

              # DOWN
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'down' and count == 1 }}"
                sequence: !input down_press_1
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'down' and count == 2 }}"
                sequence: !input down_press_2
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'down' and count == 3 }}"
                sequence: !input down_press_3
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'down' and count == 4 }}"
                sequence: !input down_press_4

              # OFF
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'off' and count == 1 }}"
                sequence: !input off_press_1
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'off' and count == 2 }}"
                sequence: !input off_press_2
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'off' and count == 3 }}"
                sequence: !input off_press_3
              - conditions:
                  - condition: template
                    value_template: "{{ button == 'off' and count == 4 }}"
                sequence: !input off_press_4

    default: []